<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ใบสั่งอาหาร | ก๋วยเตี๋ยวต้มยำบ้านลายจุดข้างวัง</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>ใบสั่งอาหาร</a></h1>
<h2>หมายเลขโต๊ะของท่าน คือ <?php echo $_POST['no'];?></h2>
<form id="form_917172" class="appnitro"  method="post" action="">
<li id="li_2" >
		<label class="description" for="element_2">ระบุเส้น </label>
		<div>
		<select class="element select medium" id="element_2" name="element_2"> 
			<option value="1" selected="selected">เลือกเส้น</option>
<option value="2" >เส้นเล็ก</option>
<option value="3" >เส้นใหญ่</option>
<option value="4" >เส้นหมี่</option>
<option value="5" >วุ้นเส้น</option>
<option value="6" >บะหมี่เหลือง</option>

		</select>
		</div> 
		</li>		
		<li id="li_5" >
		<label class="description" for="element_5">ใส่ </label>
		<span>
			<input id="element_5_1" name="element_5_1" class="element checkbox" type="checkbox" value="1" checked="checked"/>
<label class="choice" for="element_5_1">ทั้งหมด</label>
<input id="element_5_2" name="element_5_2" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_5_2">หมู</label>
<input id="element_5_3" name="element_5_3" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_5_3">ลูกชิ้น</label>
<input id="element_5_4" name="element_5_4" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_5_4">หมูสับ</label>
<input id="element_5_5" name="element_5_5" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_5_5">ตับลวก</label>

		</span> 
		</li>		<li id="li_6" >
		<label class="description" for="element_6">พิเศษ </label>
		<span>
			<input id="element_6_1" name="element_6_1" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_1">ธรรมดา (35 บาท )</label>
<input id="element_6_2" name="element_6_2" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_2">พิเศษ ไข่มะตูม (+15 บาท)</label>
<input id="element_6_3" name="element_6_3" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_2">พิเศษ ไข่มะตูม 2 ฟอง (+25 บาท)</label>
<input id="element_6_3" name="element_6_3" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_3">พิเศษ เพิ่มกุ้ง (+15 บาท)</label>
<input id="element_6_4" name="element_6_4" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_4">พิเศษ เพิ่มปลาหมึก (+15 บาท)</label>

		</span> 
		</li>		<li id="li_7" >
		<label class="description" for="element_7">รสชาติ </label>
		<span>
			<input id="element_7_1" name="element_7_1" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_7_1">เผ็ด</label>
<input id="element_7_2" name="element_7_2" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_7_2">ไม่เผ็ด</label>
<input id="element_7_3" name="element_7_3" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_7_3">น้ำใส</label>

		</span> 
		</li>
			
					


		<li id="li_3" >
		<label class="description" for="element_3">กุ้ง (ตัวหละ 55 บาท) </label>
		<div>
			<input id="element_3" name="element_3" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">หมึก (ตัวหละ 55 บาท) </label>
		<div>
			<input id="element_4" name="element_4" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		
			</ul>
			<li class="buttons">
			    <input type="hidden" name="form_id" value="917172" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>